version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:  
  publish_nuget: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key: 
    secure: B7l7MRlpDCaX+ooUhRFZqkFC5UtMdnG1g1meXmUzPPdofRFVzb9FQlg+HR/EzFTk
  skip_symbols: true
  artifact: /.*\.nupkg/
  on: 
      branch: nuget