version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: oy2iob2swqvpbarjcvcayekcx3yli4quxfjydudvk6ro64
  skip_symbols: true
  artifact: /.*\.nupkg/
  on: 
      branch: nuget